namespace FIBA_OT_sim.Model
{
    public enum StatusOfNationalTeam
    {
        COMPETING_IN_GROUP_PHASE, ELIMINATED_IN_GROUP_PHASE, 
        COMPETING_IN_QUARTERFINALS, ELIMINATED_IN_QUARTERFINALS, 
        COMPETING_IN_SEMIFINALS, COMPETING_IN_THIRD_PLACE_MATCH, LOST_IN_THIRD_PLACE_MATCH, WON_BRONZE_MEDAL, 
        COMPETING_IN_FINALS, GOT_SILVER_MEDAL, WON_GOLD_MEDAL
    }
}
